### PR TITLE
Add find package support for C# namespace keyword

### PR DESCRIPTION
**Pull request by hamzajg**
Add find package name for C# codegen

### CODE REVIEW

**Comment by jakzal** [comment]
I think it's good enough for now, but if we ever add a third language we should probably rethink how to do this better (instead of adding a third if/else block).

**Review by jakzal — APPROVED** [review]

**Comment by VaughnVernon** [comment]
> I think it's good enough for now, but if we ever add a third language we should probably rethink how to do this better (instead of adding a third if/else block).

Yes. I specified that there be a common interface with implementation per language. This would not be complex; it's actually simpler than branching.

**Comment by hamzajg** [comment]
> > I think it's good enough for now, but if we ever add a third language we should probably rethink how to do this better (instead of adding a third if/else block).
> 
> Yes. I specified that there be a common interface with implementation per language. This would not be complex; it's actually simpler than branching.

yeah, there is this interface `PackageRetriever` but it's not used, I can try to use it instead

**Comment by VaughnVernon** [comment]
> > > I think it's good enough for now, but if we ever add a third language we should probably rethink how to do this better (instead of adding a third if/else block).
> > 
> > 
> > Yes. I specified that there be a common interface with implementation per language. This would not be complex; it's actually simpler than branching.
> 
> yeah, there is this interface `PackageRetriever` but it's not used, I can try to use it instead

Just a thought: `ModuleRetriever` is language neutral and Module is a DDD tactical pattern that aligns with package and namespace.

I am confused over why Default and Agnostic match on ";" and Csharp matches on "namespace". Wouldn't there be a Java/JVM match on "package"?

**Comment by hamzajg** [comment]
> > > > I think it's good enough for now, but if we ever add a third language we should probably rethink how to do this better (instead of adding a third if/else block).
> > > 
> > > 
> > > Yes. I specified that there be a common interface with implementation per language. This would not be complex; it's actually simpler than branching.
> > 
> > 
> > yeah, there is this interface `PackageRetriever` but it's not used, I can try to use it instead
> 
> Just a thought: `ModuleRetriever` is language neutral and Module is a DDD tactical pattern that aligns with package and namespace.
> 
> I am confused over why Default and Agnostic match on ";" and Csharp matches on "namespace". Wouldn't there be a Java/JVM match on "package"?

yes, I think we can use "package" to match Default or Java/JVM, and "namespace" to match Csharp. Java/JVM is considered as default.

**Comment by VaughnVernon** [comment]
> > > > > I think it's good enough for now, but if we ever add a third language we should probably rethink how to do this better (instead of adding a third if/else block).
> > > > 
> > > > 
> > > > Yes. I specified that there be a common interface with implementation per language. This would not be complex; it's actually simpler than branching.
> > > 
> > > 
> > > yeah, there is this interface `PackageRetriever` but it's not used, I can try to use it instead
> > 
> > 
> > Just a thought: `ModuleRetriever` is language neutral and Module is a DDD tactical pattern that aligns with package and namespace.
> > I am confused over why Default and Agnostic match on ";" and Csharp matches on "namespace". Wouldn't there be a Java/JVM match on "package"?
> 
> yes, I think we can use "package" to match Default or Java/JVM, and "namespace" to match Csharp. Java/JVM is considered as default.

Excellent, but I think Default should be named Java to make it explicit. Maybe JVM is better, or even JavaLike. Kotlin, Scala, Groovy all use package. Not sure about Clojure but I doubt we'd ever support it anyway.

**Review by tjaskula — APPROVED** [review]
Looks good

**Pull request merged**
